# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stephen Asamoah — Front-End Web Developer
email: mail@stephenasamoah.com
description: > # this means to ignore newlines until "baseurl:"
  Stephen Asamoah, Junior Front-End Web Developer

author_name: Stephen Asamoah
permalink: /:categories/:title

collections:
  projects:
    #output: true

baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.webcollective.ml # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: realasamoah
github_username:  stephenasamoah
behance_username: stephenasamoah

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

#highlighter: pygments

links:
    - title: home
      url: /index
    - title: projects
      url: /projects
    - title: find me
      url: /find-me



#SassOptions
asset_path: assets
image_path: assets/images
image_url: assets/images

sass:
  style: expanded

#Environment
#JEKYLL_ENV="development"
env : production

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: ["Gemfile", "Gemfile.lock", "Gulpfile.js", "html", "node_modules", "bower_components", "bower.json", "package.json", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/",  ]